image:
  file: .gitpod.Dockerfile

tasks:
  - name: Initialize pip
    init: |
      echo 'export PIP_USER=false' >> $HOME/.bashrc
      source ~/.bashrc
      pip install -r requirements.txt
      
vscode:
  extensions:
    - ms-python.python
    - eamodio.gitlens
    - streetsidesoftware.code-spell-checker
