image:
  file: .gitpod.Dockerfile

tasks:
  - name: Initialize pip
    init: |
      pip install -r requirements.txt

vscode:
  extensions:
    - ms-python.python
    - eamodio.gitlens
    - streetsidesoftware.code-spell-checker
