image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build

ports:
  - port: 5244
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - muhammad-sammy.csharp
