image: gitpod/workspace-full:latest
ports:
- port: 8080
vscode:
  extensions:
    - charliermarsh.ruff
    - ms-python.black-formatter
    - ms-python.pylint
    - ms-python.python
    - sourcery.sourcery
    - streetsidesoftware.code-spell-checker
    - tamasfe.even-better-toml
    