[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "everything"
version = "0.0.1"
description = "The whole project"
readme = "README.md"
requires-python = ">=3.8"

classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "pip-tools",  # used to manage requirements.txt.
    "setuptools",
    "toml",
    "UnleashClient",
]

# Find all the packages in the project using automatic discovery (flat-layout).
[tool.setuptools.packages.find]
