[tool.poetry]
name = "lieutenant-green"
version = "0.1.0"
description = "TinyDb testing."
authors = ["Joe J Collins <joejcollins@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://example.com"
repository = "https://github.com/joejcollins/lieutenant-green"
documentation = "https://example.com/docs"

# Optional dependencies
dependencies = [
    "requests",
    "numpy >=1.19.0, <2.0.0"
]

# Development dependencies
dev-dependencies = [
    "pytest",
    "black",
    "isort"
]

[tool.poetry.scripts]
example-script = "lieutenant_green.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"

[tool.poetry]
packages = [
    { include = "example_project", from = "src" }
]
