backend:
  name: github
  repo: joejcollins/lieutenant-green  # Your GitHub repo
  branch: gh-pages

media_folder: "static/uploads"   # Where uploaded images will be stored in the repo
public_folder: "/uploads"        # Public URL for uploaded media files

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
