backend:
  name: github
  repo: joejcollins/lieutenant-green  # Your GitHub repo
  branch: gh-pages
  api_root: https://api.github.com
  site_domain: joejcollins.github.io/lieutenant-green
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "static/uploads"   # Where uploaded images will be stored in the repo
public_folder: "/uploads"        # Public URL for uploaded media files

site_url: https://joejcollins.github.io/lieutenant-green # GitHub Pages URL for your site

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
